#!/usr/bin/env perl

use strict; use warnings;

use FindBin qw($Bin);
use lib "$Bin/lib";
use Getopt::Long;

my $base = $Bin;

@ARGV = ('--shell') unless @ARGV;

my ($shell, $mal);
my $eval = '';
my $run = '';

GetOptions (
    "shell" => \$shell,
    "mal" => \$mal,
    "eval=s" => \$eval,
) or die("Error in command line arguments\n");

if (@ARGV) {
    if ($mal) {
        unshift @ARGV, "$base/../mal/stepA_mal.mal";
    }
    $run = $ARGV[0];
} else {
    unshift @ARGV, 'NO_SOURCE_PATH';
}

require REPL;

my $repl = REPL->new;

if ($eval) {
    if ($shell) {
        $repl->rep(qq<(do $eval)>);
        $repl->repl;
    } else {
        $repl->rep(qq<(prn (do $eval))>);
    }

} elsif ($shell) {
    $repl->repl;

} elsif ($run) {
    -f $run or die "No such file '$run'";
    $run =~ /\.mal$/ or
        die "Don't know how to run '$run'";
    $repl->rep(qq<(load-file "$run")>);

} else {
    $repl->repl;
}
