#!/usr/bin/env perl

use v5.12;

use FindBin qw($Bin);
use lib "$Bin/lib";
use Getopt::Long;

@ARGV = ('--shell') unless @ARGV;

my $shell;
my $eval = '';
my $run = '';

GetOptions (
    "shell" => \$shell,
    "eval=s" => \$eval,
) or die("Error in command line arguments\n");

if (@ARGV) {
    $run = $ARGV[0];
} else {
    unshift @ARGV, 'NO_SOURCE_PATH';
}

require REPL;

if ($eval) {
    if ($shell) {
        REPL::rep(qq<(do $eval)>);
        REPL->repl;
    } else {
        REPL::rep(qq<(prn (do $eval))>);
    }

} elsif ($shell) {
    REPL->repl;

} elsif ($run) {
    -f $run or die "No such file '$run'";
    REPL::rep(qq<(load-file "$run")>);

} else {
    REPL->repl;
}
