#!/usr/bin/env perl

use strict; use warnings;

use Cwd 'abs_path';
use FindBin qw($Bin);
use lib "$Bin/lib", abs_path("$Bin/../perl.2/lib");
use Getopt::Long;

my $base = $Bin;

@ARGV = ('--shell') unless @ARGV;

my ($shell, $mal, $ys);
my $eval = undef;
my $run = undef;

GetOptions (
    "shell" => \$shell,
    "mal" => \$mal,
    "ys" => \$ys,
    "eval=s" => \$eval,
) or die("Error in command line arguments\n");

if (@ARGV) {
    if ($mal) {
        unshift @ARGV, "$base/src/ys.mal";
    }
    elsif ($ys) {
        unshift @ARGV, "$base/src/ys.ys";
    }
    $run = $ARGV[0];
} else {
    unshift @ARGV, 'NO_SOURCE_PATH';
}

require YS::REPL;

my $repl = YS::REPL->new;

if (defined $eval) {
    if ($shell) {
        $repl->rep(qq<(do $eval)>);
        $repl->repl;
    } else {
        $repl->rep(qq<(prn (do $eval))>);
    }

} elsif ($shell) {
    $repl->repl;

} elsif ($run) {
    -f $run or die "No such file '$run'";
    $run =~ /\.(mal|ys)$/ or
        die "Don't know how to run '$run'";
    $repl->rep(qq<(load-file "$run")>);

} else {
    $repl->repl;
}
