#!/usr/bin/env bash

set -euo pipefail

root=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)

cd "$root"

if [[ ${impl-} == p* ]]; then
  perl "$root/../perl.2/repl" "$@"
else
  perl "$root/../perl.2/repl" ./lib/ys.ys "$@"
fi
